version: 2.1
jobs:
  test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Print version
          command: |
            node -v
            npm -v
      - run:
          name: Upgrade npm and node
          command: |
            curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
            sudo apt-get update
            sleep 5
            sudo apt-get install software-properties-common
            sudo apt-get install nodejs=12.18.3

workflows:
  version: 2.1
  build-deploy:
    jobs:
      - test:
          filters:
            branches:
              only: master

