version: 2.1
jobs:
  test:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/ts-hello-express
    steps:
      - checkout
      - run:
          name: Update node
          command: |
            wget https://nodejs.org/dist/v12.18.3/node-v12.18.3-linux-x64.tar.xz
            sudo apt-get install xz-utils
            tar -C /usr/local –strip-components 1 -xJf node-v12.18.3-linux-x64.tar.xz
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Run tests
          command: |
            npm run test

  build:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/ts-hello-express
    steps:
      - checkout
      - run:
          name: Build
          command: |
            npm run build

workflows:
  version: 2.1
  build-deploy:
    jobs:
      - test:
          filters:
            branches:
              only: master
      - build:
          requires:
            - test
          filters:
            branches:
              only: master

