version: 2.1
jobs:
  test:
    working_directory: ~/hello
    executor:
      name: node/default
      tag: 12.16.0
    steps:
      - checkout
      - node/install-packages:
          app-dir: hello
          cache-path: node_modules
          override-ci-command: npm i
      - run:
          name: Run tests
          command: |
            npm run test

orbs:
  node: circleci/node@4.0.0

workflows:
  version: 2.1
  build-deploy:
    jobs:
      - test:
          filters:
            branches:
              only: master

