version: 2.1
jobs:
  test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Print version
          command: |
            node -v
            npm -v
      - run:
          name: Upgrade npm and node
          command: |
            npm install -g npm@latest
            npm -v
            npm install -g node 12.18.3
workflows:
  version: 2.1
  build-deploy:
    jobs:
      - test:
          filters:
            branches:
              only: master

