version: 2.1
jobs:
  test:
    machine:
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run:
          name: Upgrade node
          command: |
            npm -v
            sudo npm install -g n
            sudo n 12.18.3
            node -v
      - run:
          name: Install npm dependencies
          command: |
            npm install
      - run:
          name: Run tests
          command: |
            npm run test

  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Build
          command: |
            npm run build

  push:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Push image
          command: |
            docker build -t $DOCKERHUB_USERNAME/ts-hello-express:$CIRCLE_SHA1 .
            echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/ts-hello-express:$CIRCLE_SHA1

workflows:
  version: 2.1
  build-deploy:
    jobs:
      - test:
          filters:
            branches:
              only: master
      - build:
          requires:
            - test
          filters:
            branches:
              only: master
      - push:
          context: dockerhub
          requires:
            - build
          filters:
            branches:
              only: master
