version: 2
jobs:
  test:
    machine:
      image: cimg/node:12.16
      docker_layer_caching: false
    working_directory: ~/hello-sts

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Run tests
          command: |
            npm run test

workflows:
  version: 2
  build-deploy:
    jobs:
      - test:
          filters:
            branches:
              only: master

