version: 2.1
jobs:
  test:
    executor:
      name: node/default
      tag: 12.16.0
    steps:
      - checkout
      - node/install-packages:
          cache-path: node_modules
          override-ci-command: npm i
      - run-command: npm run test

  build:
    executor:
      name: node/default
      tag: 12.16.0
    steps:
      - checkout
      - node/install-packages:
          cache-path: node_modules
          override-ci-command: npm i

orbs:
  node: circleci/node@4.0.0

workflows:
  version: 2.1
  build-deploy:
    jobs:
      - test:
          filters:
            branches:
              only: master
      - build:
          requires:
            - test
          filters:
            branches:
              only: master

